import {Navigate,Route,Routes,useLocation,useNavigate,useParams} from 'react-router-dom'
import {useCallback,useEffect,useRef,useState} from 'react'

type Lang='id'|'en'
const ok=(x:string|undefined):x is Lang=>x==='id'||x==='en'
const t={
 id:{name:'Destian Ricko',pos:'General Affair × Operations × Automation',intro:'Saya bekerja dari masalah operasional terlebih dahulu, lalu menggunakan teknologi ketika teknologi benar-benar memberi leverage.',about:'Saya memiliki pengalaman langsung mengelola operasional General Affair, aset, procurement, vendor, fasilitas, infrastruktur IT, dan administrasi di dua lokasi kantor.',work:'Pilihan karya',bel:{title:'BELERICK',sub:'Membangun platform operasional internal',context:'BELERICK dirancang dari perspektif workflow General Affair untuk menyatukan aset, karyawan, maintenance, purchasing, inventory, vendor, ruangan, dokumen, task, dan reporting.',quote:'BELERICK bukan hanya dibuat untuk mencatat data, tetapi untuk menjaga pengetahuan operasional perusahaan agar tidak hilang ketika orang berganti.'},sampo:'Dari laporan informal menjadi laporan operasional terstruktur',cash:'Foto struk → transaksi terstruktur',ops:'Case study operasional',contact:'Mari lanjutkan percakapannya'},
 en:{name:'Destian Ricko',pos:'General Affair × Operations × Automation',intro:'I start from the operational problem first, then use technology where it creates real leverage.',about:'I have hands-on experience managing General Affair operations, assets, procurement, vendors, facilities, IT infrastructure, and administration across two office locations.',work:'Selected work',bel:{title:'BELERICK',sub:'Building an internal operations platform',context:'BELERICK is designed from the perspective of a General Affair workflow to connect assets, employees, maintenance, purchasing, inventory, vendors, rooms, documents, tasks, and reporting.',quote:'BELERICK was not built only to record data, but to preserve operational knowledge so it does not disappear when people change.'},sampo:'From informal reports to structured operational issues',cash:'Receipt photo → structured transaction',ops:'Selected operations case studies',contact:'Let’s continue the conversation'}
}
// Single place for every screenshot. Swap `src` here to change an asset; `alt` travels with it.
const imgs={
 dash:{src:'/images/belerick/dashboard.jpg',alt:'BELERICK dashboard showing the operational overview'},
 workspace:{src:'/images/belerick/workspace.jpg',alt:'BELERICK Workspace showing tasks generated from operational rules'},
 copilot:{src:'/images/belerick/copilot.jpg',alt:'BELERICK Copilot, the assistant view for operational context'},
 assets:{src:'/images/belerick/assets.jpg',alt:'BELERICK Assets, the centralized view of company assets'},
 analytics:{src:'/images/belerick/analytics.jpg',alt:'BELERICK Operational Analytics showing asset overview, status, and age'},
 reports:{src:'/images/belerick/reports.jpg',alt:'BELERICK Reports, report output grouped by operational domain'},
 sampo:{src:'/images/it-reporting/sampo-bot.jpg',alt:'Sampo Bot conversation turning an informal report into a structured report'},
 cash:{src:'/images/petty-cash/petty-cash.jpg',alt:'AI Petty Cash Assistant recording a receipt photo sent through Telegram'}
}
type Img={src:string;alt:string}
// Compact thumbnail on the page; the full screenshot lives in the lightbox.
function Shot({i,cap,hint,onOpen,wide,md}:{i:Img;cap:string;hint:string;onOpen:(i:Img,from:HTMLElement)=>void;wide?:boolean;md?:boolean}){
 const cls=[wide?'wide':null,md?'shot-md':null].filter(Boolean).join(' ')
 return <figure className={cls||undefined}><button type="button" className="shot" onClick={(e)=>onOpen(i,e.currentTarget)}><img src={i.src} alt={i.alt} loading="lazy" decoding="async"/></button><figcaption>{cap}<span className="hint">{hint}</span></figcaption></figure>
}
function Lightbox({item,onClose,closeLabel}:{item:Img;onClose:()=>void;closeLabel:string}){
 const close=useRef<HTMLButtonElement>(null)
 useEffect(()=>{
  close.current?.focus()
  const onKey=(e:KeyboardEvent)=>{if(e.key==='Escape'){onClose()}else if(e.key==='Tab'){e.preventDefault();close.current?.focus()}}
  document.addEventListener('keydown',onKey)
  const prev=document.body.style.overflow
  document.body.style.overflow='hidden'
  return()=>{document.removeEventListener('keydown',onKey);document.body.style.overflow=prev}
 },[onClose])
 return <div className="lb" role="dialog" aria-modal="true" aria-label={item.alt} onClick={onClose}><div className="lb-inner" onClick={(e)=>e.stopPropagation()}><button ref={close} type="button" className="lb-close" onClick={onClose} aria-label={closeLabel}>×</button><img src={item.src} alt={item.alt} decoding="async"/></div></div>
}
function Shell(){const {lang}=useParams(); const l:Lang=ok(lang)?lang:'id'; const c=t[l]; const nav=useNavigate(); const loc=useLocation(); useEffect(()=>{document.documentElement.lang=l;document.title=c.name+' — '+c.pos},[l]); const other=l==='id'?'en':'id'; const [shot,setShot]=useState<Img|null>(null); const trigger=useRef<HTMLElement|null>(null); const openShot=useCallback((i:Img,from:HTMLElement)=>{trigger.current=from;setShot(i)},[]); const closeShot=useCallback(()=>{setShot(null);trigger.current?.focus()},[]); const hint=l==='id'?'Lihat lebih besar':'Click to view larger'; const closeLabel=l==='id'?'Tutup':'Close'; return <div className="page"><header><a href="#hero">Ricko</a><nav><a href="#about">About</a><a href="#work">Work</a><a href="#operations">Operations</a><a href="#contact">Contact</a><a href={`/${other}${loc.hash}`} onClick={(e)=>{e.preventDefault();nav(`/${other}${loc.hash}`)}}>{other.toUpperCase()}</a></nav></header><main>
<section id="hero" className="hero"><span className="eyebrow">{c.pos}</span><h1>{c.name}</h1><p>{c.intro}</p><div className="actions"><a className="btn primary" href="#work">{l==='id'?'Lihat karya terpilih':'View selected work'}</a><a className="btn" href="#contact">{l==='id'?'Hubungi saya':'Contact me'}</a></div></section>
<section id="about"><h2>{l==='id'?'Tentang':'About'}</h2><p>{c.about}</p></section>
<section id="work"><h2>{c.work}</h2><div className="cards"><a href="#belerick">BELERICK<span>{c.bel.sub}</span></a><a href="#sampo">AI IT Reporting Assistant<span>{c.sampo}</span></a><a href="#petty-cash">AI Petty Cash Assistant<span>{c.cash}</span></a></div></section>
<section id="belerick" className="feature"><span className="eyebrow">01 — BELERICK</span><h2>{c.bel.title}</h2><p className="sub">{c.bel.sub}</p><p>{c.bel.context}</p><blockquote>{c.bel.quote}</blockquote><h3>{l==='id'?'Dari data menjadi pekerjaan':'From data to work'}</h3><p>{l==='id'?'Operational gap → business rule → task → explanation → resolution':'Operational gap → business rule → task → explanation → resolution'}</p><div className="gallery"><Shot i={imgs.dash} cap="Dashboard — operational overview" hint={hint} onOpen={openShot} wide/><Shot i={imgs.workspace} cap="Workspace — rule-generated tasks" hint={hint} onOpen={openShot}/><Shot i={imgs.copilot} cap="Copilot — operational intelligence" hint={hint} onOpen={openShot}/><Shot i={imgs.assets} cap="Assets — centralized operational view" hint={hint} onOpen={openShot}/><Shot i={imgs.analytics} cap="Operational Analytics" hint={hint} onOpen={openShot}/><Shot i={imgs.reports} cap="Reports" hint={hint} onOpen={openShot}/></div></section>
<section id="sampo"><span className="eyebrow">02 — AI IT REPORTING ASSISTANT</span><h2>{c.sampo}</h2><p>{l==='id'?'Laporan informal → klarifikasi → laporan terstruktur → severity → tindak lanjut GA/IT':'Informal report → clarification → structured report → severity → GA/IT follow-up'}</p><Shot i={imgs.sampo} cap="Sampo Bot — selected evidence" hint={hint} onOpen={openShot} md/></section>
<section id="petty-cash"><span className="eyebrow">03 — AI PETTY CASH ASSISTANT</span><h2>{c.cash}</h2><p>{l==='id'?'Foto struk → Telegram → OCR → klasifikasi → Google Sheets':'Receipt photo → Telegram → OCR → classification → Google Sheets'}</p><Shot i={imgs.cash} cap="Petty Cash — selected evidence" hint={hint} onOpen={openShot} md/></section>
<section id="operations"><span className="eyebrow">04 — OPERATIONS</span><h2>{c.ops}</h2><div className="ops"><article><h3>{l==='id'?'Optimasi Biaya Listrik':'Electricity Cost Optimization'}</h3><p>Observed billing reduction of at least 21% across the compared office locations.</p></article><article><h3>{l==='id'?'Operasi & Maintenance PC':'PC Operations & Maintenance'}</h3><p>{l==='id'?'Sekitar 10–15 kasus/bulan diselesaikan sendiri, di luar kasus vendor, termasuk custom PC assembly.':'Approximately 10–15 cases/month independently resolved, excluding vendor cases, including custom PC assembly.'}</p></article><article><h3>{l==='id'?'Procurement Decision Support':'Procurement Decision Support'}</h3><p>{l==='id'?'Membandingkan opsi vendor berdasarkan harga, spesifikasi, garansi, ketersediaan, dan kebutuhan operasional.':'Compared vendor options across price, specifications, warranty, availability, and operational fit.'}</p></article><article><h3>{l==='id'?'Relokasi & Infrastruktur':'Office Relocation & Infrastructure'}</h3><p>{l==='id'?'Mengkoordinasikan relokasi dua kantor dan kesiapan server, internet, listrik, AC, dan workstation.':'Coordinated two-office relocation and readiness of server, internet, electricity, AC, and workstations.'}</p></article></div></section>
<section id="contact"><span className="eyebrow">CONTACT</span><h2>{c.contact}</h2><p><a href="mailto:destianricko@gmail.com">destianricko@gmail.com</a></p><p><a href="https://linkedin.com/in/destian-ricko-0a35b2225/" target="_blank" rel="noreferrer">LinkedIn</a></p><p>Jombang, Jawa Timur, Indonesia</p><a className="cv" href={l==='id'?'/cv/ricko-cv-id.pdf':'/cv/ricko-cv-en.pdf'}>{l==='id'?'Unduh CV Bahasa Indonesia':'Download English CV'}<span aria-hidden="true">→</span></a></section>
</main><footer>Operations → Analyze → Improve → Automate</footer>{shot&&<Lightbox item={shot} onClose={closeShot} closeLabel={closeLabel}/>}</div>}
export default function App(){return <Routes><Route path="/" element={<Navigate to="/id" replace/>}/><Route path="/:lang" element={<Shell/>}/><Route path="*" element={<Navigate to="/id" replace/>}/></Routes>}
